[appendix]
:appendix-caption: Annex
== Conformance Class Abstract Test Suite (Normative)

[NOTE]
Ensure that there is a conformance class for each requirements class and a test for each requirement (identified by requirement name and number)

=== Conformance Class A: URIs

Conformance class for Universal Resource Identifiers definition and interpretation.

==== Requirement 1
[cols=">20h,<80d",width="100%"]
|===
|Test id: |/conf/conf-class-a/requirement-1
|Requirement: |/req/req-class-a/requirement-1
|Test purpose: | Verify that the identity of a file is always present within the RDF graph parsed from that file.
|Test method: | Inspect the identity of the Container, within the parsed RDF graph, representing the root group of the netCDF file and validate that it matches the input parameter, or default value, for that file.
|===

==== Requirement 2

[cols=">20h,<80d",width="100%"]
|===
|Test id: |/conf/conf-class-a/requirement-2
|Requirement: |/req/req-class-a/requirement-2
|Test purpose: | Verify that the identity of variables and groups within a file are defined relative to the defined file identity.
|Test method: | Inspect the identity of the variables and containers, within the parsed RDF graph, representing the contents of the root group of the netCDF file and validate that their identifiers are all defined as a combination of the file identity and the variable / container identity.
|===


Identity:
----
http://secret.binary-array-ld.net/identity.nc
----

Input NetCDF File - Defined in CDL:
https://raw.githubusercontent.com/opengeospatial/netcdf-ld/master/standard/abstract_tests/CDL/ogcClassA.cdl
----
include::abstract_tests/CDL/ogcClassA.cdl[]
----

Validated output RDF graph:
https://raw.githubusercontent.com/opengeospatial/netcdf-ld/master/standard/abstract_tests/TTL/ogcClassA.ttl
----
include::abstract_tests/TTL/ogcClassA.ttl[]

----


=== Conformance Class B: Prefixing


==== Requirement 1

[cols=">20h,<80d",width="100%"]
|===
|Test id: |/conf/conf-class-a/requirement-2
|Requirement: |/req/req-class-a/requirement-2
|Test purpose: | Verify that defined prefixes within a file are recognised and used to expand prefix notation attribute names and values.
|Test method: | Inspect the predicates and objects, within the parsed RDF graph, and verify that all prefix quantities are expanded to the correct URIs.
|===


Identity:
----
http://secret.binary-array-ld.net/prefix.nc
----

Input NetCDF File - Defined in CDL:
https://raw.githubusercontent.com/opengeospatial/netcdf-ld/master/standard/abstract_tests/CDL/ogcClassB.cdl
----
include::abstract_tests/CDL/ogcClassB.cdl[]
----

Validated output RDF graph:
https://raw.githubusercontent.com/opengeospatial/netcdf-ld/master/standard/abstract_tests/TTL/ogcClassB.ttl
----
include::abstract_tests/TTL/ogcClassB.ttl[]

----


=== Conformance Class C: Aliasing

Identity:
----
http://secret.binary-array-ld.net/alias.nc
----

Alias Graph
----
http://def.scitools.org.uk/NetCDF
----


Input NetCDF File - Defined in CDL:
https://raw.githubusercontent.com/opengeospatial/netcdf-ld/master/standard/abstract_tests/CDL/ogcClassC.cdl
----
include::abstract_tests/CDL/ogcClassC.cdl[]
----

Validated output RDF graph:
https://raw.githubusercontent.com/opengeospatial/netcdf-ld/master/standard/abstract_tests/TTL/ogcClassC.ttl
----
include::abstract_tests/TTL/ogcClassC.ttl[]

----



=== Conformance Class D: Attribute Names

Identity:
----
http://secret.binary-array-ld.net/attributes.nc
----

Alias Graph
----
http://def.scitools.org.uk/NetCDF
----


Input NetCDF File - Defined in CDL:
https://raw.githubusercontent.com/opengeospatial/netcdf-ld/master/standard/abstract_tests/CDL/ogcClassD.cdl
----
include::abstract_tests/CDL/ogcClassD.cdl[]
----

Validated output RDF graph:
https://raw.githubusercontent.com/opengeospatial/netcdf-ld/master/standard/abstract_tests/TTL/ogcClassD.ttl
----
include::abstract_tests/TTL/ogcClassD.ttl[]

----



=== Conformance Class E: Variable-to-variable Referencing


