[appendix]
:appendix-caption: Annex
== Conformance Class Abstract Test Suite (Normative)

[NOTE]
Ensure that there is a conformance class for each requirements class and a test for each requirement (identified by requirement name and number)

=== Conformance Class A: URIs

Conformance class for Universal Resource Identifiers definition and interpretation.

==== Requirement 1
[cols=">20h,<80d",width="100%"]
|===
|Test id: |/conf/conf-class-a/requirement-1
|Requirement: |/req/req-class-a/requirement-1
|Test purpose: | Verify that the identity of a file is always present within the RDF graph parsed from that file.
|Test method: | Inspect the identity of the Container, within the parsed RDF graph, representing the root group of the netCDF file and validate that it matches the input parameter, or default value, for that file.
|===

==== Requirement 2

[cols=">20h,<80d",width="100%"]
|===
|Test id: |/conf/conf-class-a/requirement-2
|Requirement: |/req/req-class-a/requirement-2
|Test purpose: | Verify that the identity of variables and groups within a file are defined relative to the defined file identity.
|Test method: | Inspect the identity of the variables and containers, within the parsed RDF graph, representing the contents of the root group of the netCDF file and validate that their identifiers are all defined as a combination of the file identity and the variable / container identity.
|===


Identity:
----
http://secret.binary-array-ld.net/identity.nc
----

Input NetCDF File - Defined in CDL:
----
netcdf ogcClassA {
dimensions:
        d0 = 1 ;
        d1 = 1 ;
variables:
        int var0 ;
        int var1 ;

data:
}

----

Validated output RDF graph:
----
@prefix bald: <https://www.opengis.net/def/binary-array-ld/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix this: <http://secret.binary-array-ld.net/identity.nc/> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://secret.binary-array-ld.net/identity.nc> a bald:Container ;
    bald:contains this:var0,
        this:var1 .

this:var0 a bald:Resource .

this:var1 a bald:Resource .

----


=== Conformance Class B: Prefixing


==== Requirement 1

[cols=">20h,<80d",width="100%"]
|===
|Test id: |/conf/conf-class-a/requirement-2
|Requirement: |/req/req-class-a/requirement-2
|Test purpose: | Verify that defined prefixes within a file are recognised and used to expand prefix notation attribute names and values.
|Test method: | Inspect the predicates and objects, within the parsed RDF graph, and verify that all prefix quantities are expanded to the correct URIs.
|===


Identity:
----
http://secret.binary-array-ld.net/prefix.nc
----

Input NetCDF File - Defined in CDL:
----
netcdf ogcClassB {
dimensions:
        d0 = 1 ;
	d1 = 1 ;
variables:
	int var0 ;
	    var0:rdfs__label = "rdfs__label" ;
	int var1 ;
	    var1:rdfs__label = "rdfs__label" ;
        int prefix_list ;
            prefix_list:bald__ = "https://www.opengis.net/def/binary-array-ld/" ;
            prefix_list:rdf__ = "http://www.w3.org/1999/02/22-rdf-syntax-ns#" ;
            prefix_list:rdfs__ = "http://www.w3.org/2000/01/rdf-schema#" ;
        :bald__isPrefixedBy = "prefix_list" ;
data:
}
----

Validated output RDF graph:
----
@prefix bald: <https://www.opengis.net/def/binary-array-ld/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix this: <http://secret.binary-array-ld.net/prefix.nc/> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://secret.binary-array-ld.net/prefix.nc> a bald:Container ;
    bald:contains this:var0,
        this:var1 ;
    bald:isPrefixedBy "prefix_list" .

this:var0 a bald:Resource ;
    rdfs:label rdfs:label .

this:var1 a bald:Resource ;
    rdfs:label rdfs:label .

----

=== Conformance Class C: Aliasing

Identity:
----
http://secret.binary-array-ld.net/alias.nc
----

Input NetCDF File - Defined in CDL:
----
netcdf ogcClassC {
dimensions:
        d0 = 1 ;
	d1 = 1 ;
variables:
	int var0 ;
	int var1 ;
:title = "Sample netCDF file definition with alias terms from the netCDF user guide" ;
data:
}
----

Alias Graph
----
http://def.scitools.org.uk/NetCDF
----


Validated output RDF graph:
----
@prefix NetCDF: <http://def.scitools.org.uk/NetCDF/> .
@prefix bald: <https://www.opengis.net/def/binary-array-ld/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix this: <http://secret.binary-array-ld.net/alias.nc/> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://secret.binary-array-ld.net/alias.nc> a bald:Container ;
    bald:contains this:var0,
        this:var1 ;
    NetCDF:title "Sample netCDF file definition with alias terms from the netCDF user guide" .

this:var0 a bald:Resource .

this:var1 a bald:Resource .

----


=== Conformance Class D: Attribute Names

Identity:
----
http://secret.binary-array-ld.net/attributes.nc
----

Input NetCDF File - Defined in CDL:
----
netcdf ogcClassD {
dimensions:
        d0 = 1 ;
	d1 = 1 ;
variables:
	int var0 ;
	    var0:rdfs__label = "rdfs__label" ;
	int var1 ;
	    var1:rdfs__label = "rdfs__label" ;
        int prefix_list ;
            prefix_list:bald__ = "https://www.opengis.net/def/binary-array-ld/" ;
            prefix_list:rdf__ = "http://www.w3.org/1999/02/22-rdf-syntax-ns#" ;
            prefix_list:rdfs__ = "http://www.w3.org/2000/01/rdf-schema#" ;
        :bald__isPrefixedBy = "prefix_list" ;
	:title = "Sample netCDF file definition with alias terms from the netCDF user guide" ;
data:
}
----

Alias Graph
----
http://def.scitools.org.uk/NetCDF
----


Validated output RDF graph:
----
@prefix NetCDF: <http://def.scitools.org.uk/NetCDF/> .
@prefix bald: <https://www.opengis.net/def/binary-array-ld/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix this: <http://secret.binary-array-ld.net/attributes.nc/> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://secret.binary-array-ld.net/attributes.nc> a bald:Container ;
    bald:contains this:var0,
        this:var1 ;
    bald:isPrefixedBy "prefix_list" ;
    NetCDF:title "Sample netCDF file definition with alias terms from the netCDF user guide" .

this:var0 a bald:Resource ;
    rdfs:label rdfs:label .

this:var1 a bald:Resource ;
    rdfs:label rdfs:label .

----



=== Conformance Class E: Variable-to-variable Referencing


