== References
The following normative documents contain provisions that, through reference in this text, constitute provisions of this document. For dated references, subsequent amendments to, or revisions of, any of these publications do not apply. For undated references, the latest edition of the normative document referred to applies.

Patrick J. Hayes, Peter F. Patel-Schneider. RDF 1.1 Semantics. W3C Recommendation, 25 February 2014. URL: http://www.w3.org/TR/2014/REC-rdf11-mt-20140225/. The latest edition is available at http://www.w3.org/TR/rdf11-mt/

Eric Prud'hommeaux, Gavin Carothers. RDF 1.1 Turtle: Terse RDF Triple Language. W3C Recommendation, 25 February 2014. URL: http://www.w3.org/TR/2014/REC-turtle-20140225/. The latest edition is available at http://www.w3.org/TR/turtle/

Steve Harris, Andy Seaborne. SPARQL 1.1 Query Language, W3C Recommendation, 21 March 2013, URL: ttp://www.w3.org/TR/sparql11-query/, (2013).

Miles, A., Bechhofer, S.: SKOS Simple Knowledge Organization System Reference. (2008).

OGC: NetCDF Core Encoding Standard version 1.0, http://portal.opengeospatial.org/files/?artifact_id=43732, (2011).

OGC: CF-netCDF Core and Extensions Primer, http://portal.opengeospatial.org/files/?artifact_id=43733, (2011).


W3C: RDF 1.1 Turtle, https://www.w3.org/TR/turtle/, (2014).

W3C: RDF 1.1 XML Syntax, https://www.w3.org/TR/rdf-syntax-grammar/, (2014).

W3C: Notation3 (N3): A readable RDF syntax, https://www.w3.org/TeamSubmission/n3/, (2011)

W3C: SKOS Simple Knowledge Organization System Reference, (2009).

W3C: Resource Description Framework (RDF): Concepts and Abstract Syntax, (2004).

