== Terms and Definitions
This document uses the terms defined in Sub-clause 5.3 of [OGC 06-121r8], which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this standard.

For the purposes of this document, the following additional terms and definitions apply.

=== *RDF*
The Resource Description Framework (RDF) is a standard model for data exchange on the World Wide Web. RDF is specifically designed to allow the exchange of data, even where underlying schemas are different, through the use of a normalised data model of subject-predicate-object triples and using Uniform Resource Identifiers to define terms within the triples.

=== *RDF statement (or triple)*
A triple is the atomic data entity in RDF. It is a set of three entities used to make a statement about the subject of the triple. The triple takes the form subject-predicate-object (e.g. "The sea - has colour - blue"). In a Linked Data system, as many of the portions of the expression as possible are defined by URIs. RDF statements are often called "triples".

=== *RDF graph*
An RDF graph is a combination of a number of triples or RDF statements. An RDF graph may be thought of in terms of the concepts from the branch of mathematics known as graph theory. In an RDF graph, the subject and object portions of the triple form the nodes (or vertices) of the graph, while the predicate is used to label the edges (or connectors between the nodes) of the graph.

=== *URI*
A Uniform Resource Identifier (URI) is a string of characters which identifies a logical or physical resource. Uniformity of URIs comes through a set of predefined syntactic rules. The most common form of URI is the Uniform Resource Locator (URL), which is frequently refered to in common parlance as a 'web address.'

=== *Literal*
Within RDF, literals are the lexical representations of values such as numbers or dates, and literals are therefore not defined by URIs.

=== *CDL*
The Common Data Language (CDL) is a human readable notation for describing netCDF objects and data.
