==== Requirement B-4


[width="90%",cols="2,6"]
|===
|*Requirement B-4* {set:cellbgcolor:#CACCCE}|/req/req-class-b/requirement-4 +
 +

Prefixes shall be interpreted from provided JSON-LD context files at run time.


 {set:cellbgcolor:#FFFFFF}

|===

==== Requirement B-5


[width="90%",cols="2,6"]
|===
|*Requirement B-5* {set:cellbgcolor:#CACCCE}|/req/req-class-b/requirement-5 +
 +



A prefix attribute name, defined in a JSON-LD context file, shall use the limited character set:

`+[a-zA-z0-9_]+`

A prefix attribute name, defined in a JSON-LD context file, shall have the double-underscore sub-string:

`+__+`

appended to the provided string.


 {set:cellbgcolor:#FFFFFF}

|===


==== Requirement B-6

[width="90%",cols="2,6"]
|===
|*Requirement B-6* {set:cellbgcolor:#CACCCE}|/req/req-class-b/requirement-6 +
 +


A prefix value, defined in a JSON-LD context file, shall be a HTTP URI or a HTTPS URI.

A prefix value, defined in a JSON-LD context file, shall end in either a `/` or a `#` (a valid URI separator).

 
 {set:cellbgcolor:#FFFFFF}

|===

==== Requirement B-7

[width="90%",cols="2,6"]
|===
|*Requirement B-7* {set:cellbgcolor:#CACCCE}|/req/req-class-b/requirement-7 +
 +


If a prefix string is defined multiple times in provided JSON-LD context files with different URI interpretations, then implementations shall ignore that prefix and treat the prefix as locally unresolved.

 
 {set:cellbgcolor:#FFFFFF}

|===


==== Requirement B-8

[width="90%",cols="2,6"]
|===
|*Requirement B-8* {set:cellbgcolor:#CACCCE}|/req/req-class-b/requirement-8 +
 +

Prefix definitions provided explicitly within a file shall not be overwridden be context files.  Prefixes defined within a file have precedence.

If a prefix defined within a file is also defined within provided JSON-LD context files with different URI interpretations, then implementations shall ignore that JSON-LD context definition and treat the prefix as locally resolved.

This standard does not consider this as a parsing error.

Implementations may treat this condition as a warning condition and as a validation error within the provided context.

 
 {set:cellbgcolor:#FFFFFF}

|===
