==== Requirement E-4

[width="90%",cols="2,6"]
|===
|*Requirement E-4* {set:cellbgcolor:#CACCCE}|/req/req-class-e/requirement-4 +
+

A variable to variable reference is defined in Requirement E-2


Each variable to variable reference between two variables, both of which are defined with respect to one or more dimensions, shall be described by the statement.


 `+<$sourceEntity> <https://www.opengis.net/def/binary-array-ld/references> <$referenceEntity> .+`

and the definition of a `+<$referenceEntity>+`, an instance of `+<https://www.opengis.net/def/binary-array-ld/Reference>+`.  This entity carries the broadcast relationship details and the reference to the target variable.


 `+<$referenceEntity> a <https://www.opengis.net/def/binary-array-ld/Reference> ;+`

`+OPTIONAL(<https://www.opengis.net/def/binary-array-ld/sourceRefShape> ($d1 $d2 $d3) ;)+`

`+<https://www.opengis.net/def/binary-array-ld/targetRefShape> ($d4 $d5 $d6) ;+`

`+<https://www.opengis.net/def/binary-array-ld/target> <$targetEntity> .+`

`$dn` are all defined to be integers.

The object of the `<https://www.opengis.net/def/binary-array-ld/sourceRefShape>` and `<https://www.opengis.net/def/binary-array-ld/targetRefShape>` statements are each an RDF list of integer elements.

Each integer element shall be taken directly from the named dimension size defined within the input netCDF file.

If the sourceRefShape is not provided, this is inferred to be the same as the defined `bald:shape`.

The lengths of these two RefShape lists shall be the same.

The product of the sourceRefShape (if provided) elements shall match the product of the `bald:shape`, the number of elements shall be the same.

The product of the targetRefShape elements shall match the product of the `bald:shape` of the <$targetEntity>, the number of elements shall be the same.

The creation of this bald:references definition within the metadata graph is in addition to the explicit statement interpreted from the netCDF file.
The exception to this is where the netCDF file explicitly uses the bald:references attribute (bald__references). In this exception case, then the derived statement replaces the explicit statement.

 {set:cellbgcolor:#FFFFFF}

|===
