[big]*i.     Abstract*

netCDF is a format for encoding array-oriented scientific data, particularly in many Earth & Space Science domains, 
and is an Open Geospatial Consortium (OGC) standard.
While netCDF is strictly a self-describing format, a common practice to aid interoperability is to use the Climate and Forecasting (CF) 
convention and the Attribute Convention for Data Discovery (ACDD) convention. 
Several communities are defining additional netCDF conventions for describing the semantics relating of their different domains. 
As the concurrent use of multiple, and possibly clashing, netCDF conventions spreads the challenge of finding a common mechanism 
to validate and interpret metadata being embedded inside netCDF files grows.

Linked Data (LD) describes a method for encoding and publishing metadata to expose and connect data both within individual datasets and across multiple datasets. 
LD also allows dataset descriptions to become more useful through the ability to run semantically-enabled queries across datasets. 
Publishing netCDF file descriptions using LD methods presents the user community with an opportunity to address this exposure and connection and, 
further, to enhance data findability and re-use.

netCDF-Classic-LD is a standard for encoding 


[big]*ii.    Keywords*

The following are keywords to be used by search engines and document catalogues.

ogcdoc, OGC document,  netCDF, Linked Data

[big]*iii.   Preface*

[NOTE]
====
Insert Preface Text here. Give OGC specific commentary: describe the technical content, reason for document, history of the document and precursors, and plans for future work. >
Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.
====
[big]*iv.    Submitting organizations*

The following organizations submitted this Document to the Open Geospatial Consortium (OGC):

* UK Met Office
* CSIRO
* NOAA
* Marine Institute, Ireland
* HDF Group

[big]*v.     Submitters*

All questions regarding this submission should be directed to the editor or the submitters:

[%header,cols=2*] 
|===
|Name  
|Affiliation

|Mark Hedley
|UK Met Office

|Jonathan Yu
|CSIRO

|James Biard
|NOAA

|Adam Leadbetter
|Marine Institute, Ireland

|Aleksander Jelenak
|HDF Group
|===


