== Clauses not Containing Normative Material

=== Design principles and Rationale ===

netCDF-Classic-LD allows existing netCDF files to be interpreted as Linked Data with minimal changes. netCDF-Classic-LD encoding rules and mechanisms allow users to leverage Linked Data in programming environments using netCDF and to improve interoperability for netCDF files using different combinations of metadata conventions.

A design principle of netCDF-Classic-LD is that it works with existing netCDF classic encoded files. This means existing netCDF libraries can be used to parse files encoded as netCDF-Classic-LD. This also ensures that netCDF-Classic-LD files can be used as simply as netCDF, with no knowledge of RDF.

A key aspect of netCDF-Classic-LD is the introduction of rules for mapping identifiers for netCDF global and variable attributes and variables to IRIs via prefixes and aliases mechanisms. Using these mechanisms, netCDF-Classic-LD provides a way to disambiguate attribute names and values shared among different netCDF files. Identifiers are the building blocks for defining unambiguous semantics via concept definitions and relationships between concepts.

netCDF-Classic-LD aims to enable any netCDF file to be represented as RDF, if desired, for use with other Linked Data technologies like SPARQL. People intending to use netCDF-LD with RDF tools will find it can be used as another RDF syntax, like Turtle (TURTLE Ref!!).s


=== Resource Description Framework

The Resource Description Framework (RDF) is a W3 standard (ref!!).  Information elements are statements which have three parts: Subject, Predicate, Object.

Subjects and Predicates are Universal Resource Identifiers (URIs) whilst Objects may be URIs or Literals.  Where an Object is a URI, this may also be a subject for another statement.

Statements are collected together within an RDF Graph.

This standard maps the netCDF Classic data model encoding onto the RDF information model.




=== Metadata RDF Graph

An RDF graph representing the metadata of multiple files provides a valuable resource for summarising the file collection.

The numerical data within the file is not encoded within the graph, only the metadata.  In general this means that the graph is orders of magnitude smaller than the data file it summarises.

Having an RDF graph of metadata across a file collection enables the use of semantic web technologies to explore, interrogate and visualise the metadata in a variety of ways.

The following sections of this standard define how to interpret a netCDF file as an RDF metadata graph.

Multiple graphs may be combined into a single multi-file metadata graph as long as individual file identity is unique across the multiple graph.

==== Universal Resource Identifiers within netCDF files

At the core of this standard is the mechanism for encoding and interpreting Universal Resource Identifiers (URIs) within netCDF files.

These URIs may be declared explicitly within the files, or interpreted from file metadata and external information sources.


==== Identity


A netCDF file has an identity.  This identity provides the mechanism to obtain the file.  As such it is mutable, it is dependent on how the file is provided.  Two systems may provide an identical file, but in different ways, and hence use different identities.

An explicit identity may be provided during file interpretation.  If no identity is provided, a default identity, a local file URI, will be used.

Each variable within that file has its own identity, defined relative to the file identity.  This is defined using the variable name appended to the file identity and separated by a '/'.

==== Prefix Definition

==== Alias Definition

Alongside the definition of prefixes, explicit aliases may be defined within the file, or as a scope for a file during parsing.  Aliases enable controlled attribute names to be interpreted as URIs.

The aliases mechanism is less flexible than the prefixes mechanism.  It does enable interpretation of atribute names directly, making it useful for existing standards and existing files.


Aliases are applied across the file they are declared for.

Aliases are declared as a set of RDF graphs. These RDF graphs are commonly provided as URIs, to be obtained during parsing and file metadata interpretation.

The RDF graphs shall be combined and treated as a single alias scope for the file.



==== Attribute Names

In order to map netCDF metadata to RDF, all global and variable attributes are interpreted as RDF statements.  This requires that all attribute names are interpreted as URIs.

A parsing process shall map attribute names to URIs using prefix definitions first, then map attribute names to URIs aliases.


An attribute name shall be mapped to an alias URI if and only if there is an exact match for the full attribute name as a dct:notation (expand to full uri) for an entity within the alias graph where that entity declares a statement <entity> <rdf:type> <rdfs:ObjectProperty> (full URIs).

If multiple aliases match an attribute name, this is an error condition, the declared alias scope cannot be uniquely applied to the file.



All remaining attribute names shall be mapped to local identifiers, using the file identity and variable identity (ref{}) to form a locally applicable URI.


==== Attribute Values

In RDF, objects may be Literals or URIs, therefore attribute values are conditionally interpreted as Literals or as URIs.

A parsing process shall map attribute values to URIs using identified prefixes first.

===== Attribute Variable References

The value of a variable attribute may be an internal reference to another variable within the file.

For a variable reference to be declared, three conditions shall be met.

Condition one: the value is a string which exactly matches the name of a variable within the file.

Condition two: the attribute name is already interpreted as a URI, defining an entity, external to the file.

Condition three: the attribute name entity declares and <rdfs:range> of <bald:subject>.

An identified attribute reference shall map the attribute value to the identify of the matched variable within the file.

This identification takes place after prefixes are identified and mapped.

===== Attribute Value Aliases

After prefix and reference interpretation, remaining attribute values are mapped to URIs using the alias graph.

An attribute value shall be mapped to an alias URI if and only if there is an exact match for the full attribute value as a dct:notation (expand to full uri) for an entity within the alias graph.

If multiple aliases match an attribute name, this is an error condition, the declared alias scope cannot be uniquely applied to the file.

===== Attribute Value Literals

All remaining attribute values shall be left unchanged and declared as instances of <rdf:Literal>.

=== NetCDF Dimensions
