== Clauses not Containing Normative Material

=== Design principles and Rationale ===

netCDF-Classic-LD allows existing netCDF files to be interpreted as Linked Data with minimal changes. netCDF-Classic-LD encoding rules and mechanisms allow users to leverage Linked Data in programming environments using netCDF and to improve interoperability for netCDF files using different combinations of metadata conventions.

A design principle of netCDF-Classic-LD is that it works with existing netCDF classic encoded files. This means existing netCDF libraries can be used to parse files encoded as netCDF-Classic-LD. This also ensures that netCDF-Classic-LD files can be used as simply as netCDF, with no knowledge of RDF.

A key aspect of netCDF-Classic-LD is the introduction of rules for mapping identifiers for netCDF global and variable attributes and variables to IRIs via prefixes and aliases mechanisms. Using these mechanisms, netCDF-Classic-LD provides a way to disambiguate attribute names and values shared among different netCDF files. Identifiers are the building blocks for defining unambiguous semantics via concept definitions and relationships between concepts.

netCDF-Classic-LD aims to enable any netCDF file to be represented as RDF, if desired, for use with other Linked Data technologies like SPARQL. People intending to use netCDF-LD with RDF tools will find it can be used as another RDF syntax, like Turtle (TURTLE Ref!!).s


=== Resource Description Framework

The Resource Description Framework (RDF) is a W3 standard (ref!!).  Information elements are statements which have three parts: Subject, Predicate, Object.

Subjects and Predicates are Universal Resource Identifiers (URIs) whilst Objects may be URIs or Literals.  Where an Object is a URI, this may also be a subject for another statement.

Statements are collected together within an RDF Graph.

This standard maps the netCDF Classic data model encoding onto the RDF information model.




=== Metadata RDF Graph

An RDF graph representing the metadata of multiple files provides a valuable resource for summarising the file collection.

The numerical data within the file is not encoded within the graph, only the metadata.  In general this means that the graph is orders of magnitude smaller than the data file it summarises.

Having an RDF graph of metadata across a file collection enables the use of semantic web technologies to explore, interrogate and visualise the metadata in a variety of ways.

=== Universal Resource Identifiers within netCDF files

At the core of this standard is the mechanism for encoding and interpreting Universal Resource Identifiers (URIs) within netCDF files.

These URIs may be declared explicitly within the files, or interpreted from file metadata and external information sources.


==== Identity


A netCDF file has an identity.  This identity provides the mechanism to obtain the file.  As such it is mutable, it is dependent on how the file is provided.  Two systems may provide an identical file, but in different ways, and hence use different identities.

An explicit identity may be provided during file interpretation.  If no identity is provided, a default identity, a local file URI, will be used.

Each variable within that file has its own identity, defined relative to the file identity.  This is defined using the variable name appended to the file identity and separated by a '/'.

==== Prefix Definition

==== Alias Definition

==== Attribute Names

In order to map netCDF metadata to RDF, all global and variable attributes are interpreted as RDF statements.  This requires that all attribute names are interpreted as URIs.

==== Attribute Variable References


==== Attribute Values

In RDF objects may be Literals or URIs, therefore attribute values are conditionally interpreted as Literals or as URIs.


=== NetCDF Dimensions
